name: 'Slack notify'
description: 'Notify #gha about the github workflow status'
inputs:
  channel-id:
    description: 'Channel to post the message to'
    required: true
    default: 'general'
  slack-bot-token:
    description: Slack bot user token
    required: true
runs:
  using: "composite"
  steps:
    - run: echo Workflow status.
      shell: bash
    - id: slack
      name: Post to a Slack channel
      uses: slackapi/slack-github-action@v1.21.0
      with:
        channel-id: ${{ inputs.channel-id }}
        slack-message: "GitHub build result: ${{ github.action_status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack-bot-token }}