name: 'Slack notify'
description: 'Notify #gha about the github workflow status'
inputs:
  channel-id:
    description: 'Channel to post the message to'
    required: true
    default: 'general'
  slack-bot-token:
    description: Slack bot user token
    required: true
runs:
  using: "composite"
  steps:
    - id: workflow-status
      run: |
        url="${{ github.api_url }}/repos"
        repo="${{ github.repository }}"
        run_id="${{ github.run_id }}"
        token="${{ github.token }}"

        failure=$(curl -s -H "Authorization: Bearer ${token}" -H "Accept: application/vnd.github+json" \
        "${url}/${repo}/actions/runs/${run_id}/jobs" | \
        jq -r '.jobs[] | select(.status == "completed" and .conclusion == "failure").conclusion' | \
        wc -l)
        cancelled=$(curl -s -H "Authorization: Bearer ${token}" -H "Accept: application/vnd.github+json" \
        "${url}/${repo}/actions/runs/${run_id}/jobs" | \
        jq -r '.jobs[] | select(.status == "completed" and .conclusion == "cancelled").conclusion' | \
        wc -l)

        if [ "${failure}" -gt 0 ]; then
          status="failure"
        elif [ "${cancelled}" -gt 0 ]; then
          status="cancelled"
        else 
          status="success"
        fi
        
        echo "::set-output name=status::${status}"

      shell: bash

    - id: notify
      name: Post to a Slack channel
      uses: slackapi/slack-github-action@v1.21.0
      with:
        channel-id: ${{ inputs.channel-id }}
        slack-message: "GitHub build result: ${{ steps.workflow-status.outputs.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack-bot-token }}